# Lovelace Soft UI by @N-l1

# Custom header config
custom_header:
  active_tab_color: var(--sidebar-selected-icon-color)
  background: transparent
  compact_mode: true
  elements_color: var(--primary-text-color)
  hide_ch_settings: true
  hide_help: true
  notification_dot_color: var(--sidebar-selected-icon-color)
  tab_indicator_color: var(--sidebar-selected-icon-color)

# Lovelace title
title: My home

# Popup Remote
popup_cards:
  switch.tv:
    card:
      entities:
        - cards:
            - icon: 'mdi:power'
              show_icon: true
              show_name: false
              style: |
                ha-card {
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                    {% endif %}
                }
              styles:
                card:
                  - width: 60px
                  - height: 60px
                  - margin: 10px 10px 10px 155px
                  - border-radius: 100px
                  - background-color: var(--primary-background-color)
                icon:
                  - color: var(--primary-text-color)
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: power
                  entity_id: remote.xiaomi
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
        - cards:
            - entities:
                - cards:
                    - icon: 'mdi:menu-up'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - margin-left: 69px
                          - box-shadow: none
                          - width: 50px
                          - height: 50px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: up
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                  type: 'custom:hui-horizontal-stack-card'
                - cards:
                    - icon: 'mdi:menu-left'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - margin-left: 11px
                          - box-shadow: none
                          - width: 50px
                          - height: 50px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: left
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                    - name: OK
                      show_icon: false
                      show_name: true
                      style: |
                        ha-card {
                          box-shadow:
                            {% if is_state('sun.sun', 'above_horizon') %}
                              -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                            {% elif is_state('sun.sun', 'below_horizon') %}
                              -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                            {% endif %}
                        }
                      styles:
                        card:
                          - width: 50px
                          - height: 50px
                          - border-radius: 100px
                          - background-color: var(--primary-background-color)
                        name:
                          - font-size: 20px
                          - font-weight: bold
                          - font-family: Helvetica
                          - letter-spacing: '-0.01em'
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: enter
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                    - icon: 'mdi:menu-right'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - box-shadow: none
                          - width: 50px
                          - height: 50px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: right
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                  type: 'custom:hui-horizontal-stack-card'
                - cards:
                    - icon: 'mdi:menu-down'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - margin-left: 69px
                          - box-shadow: none
                          - width: 50px
                          - height: 50px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: down
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                  type: 'custom:hui-horizontal-stack-card'
              show_header_toggle: false
              style: |
                ha-card {
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      inset -3px -3px 5px rgba(255,255,255,.65), inset 3px 3px 5px rgba(0,0,0,.035);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      inset -3px -3px 5px rgba(50, 50, 50,.5), inset 3px 3px 5px rgba(0,0,0,.3);
                    {% endif %}
                  border-radius: 30px;
                  background-color: var(--primary-background-color)
                }
              type: 'custom:hui-entities-card'
          type: 'custom:hui-horizontal-stack-card'
        - show_icon: false
          show_name: false
          style: |
            ha-card {
              --ha-card-background: none !important;
              box-shadow: none !important;
            }
          styles:
            card:
              - width: 10px
              - height: 10px
          type: 'custom:button-card'
        - cards:
            - entities:
                - cards:
                    - icon: 'mdi:minus'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - margin-left: 30px
                          - box-shadow: none
                          - width: 30px
                          - height: 30px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: volume_down_pioneer
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                    - name: VOL
                      show_icon: false
                      show_name: true
                      styles:
                        card:
                          - margin-left: 10px
                          - box-shadow: none
                          - width: 30px
                          - height: 30px
                          - border-radius: 100px
                          - background-color: var(--primary-background-color)
                        name:
                          - font-size: 13px
                          - font-weight: bold
                          - font-family: Helvetica
                          - letter-spacing: '-0.01em'
                      type: 'custom:button-card'
                    - icon: 'mdi:plus'
                      show_icon: true
                      show_name: false
                      size: 100%
                      styles:
                        card:
                          - margin-left: 10px
                          - box-shadow: none
                          - width: 30px
                          - height: 30px
                          - background-color: var(--primary-background-color)
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: remote.send_command
                        service_data:
                          command: volume_up_pioneer
                          entity_id: remote.xiaomi
                      type: 'custom:button-card'
                  type: 'custom:hui-horizontal-stack-card'
              show_header_toggle: false
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                    {% endif %}
                }
              type: 'custom:hui-entities-card'
          type: 'custom:hui-horizontal-stack-card'
        - cards:
            - icon: 'mdi:home'
              show_icon: true
              show_name: false
              style: |
                ha-card {
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                    {% endif %}
                }
              styles:
                card:
                  - margin-top: 10px
                  - margin-left: 5px
                  - width: 60px
                  - height: 60px
                  - border-radius: 15px
                  - background-color: var(--primary-background-color)
                icon:
                  - color: var(--primary-text-color)
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: home
                  entity_id: remote.xiaomi
              type: 'custom:button-card'
            - icon: 'mdi:keyboard-return'
              show_icon: true
              show_name: false
              style: |
                ha-card {
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                    {% endif %}
                }
              styles:
                card:
                  - margin-top: 10px
                  - margin-left: 8px
                  - width: 60px
                  - height: 60px
                  - border-radius: 15px
                  - background-color: var(--primary-background-color)
                icon:
                  - color: var(--primary-text-color)
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: return
                  entity_id: remote.xiaomi
              type: 'custom:button-card'
            - icon: 'mdi:amazon-alexa'
              show_icon: true
              show_name: false
              style: |
                ha-card {
                  box-shadow:
                    {% if is_state('sun.sun', 'above_horizon') %}
                      -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
                    {% elif is_state('sun.sun', 'below_horizon') %}
                      -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
                    {% endif %}
                }
              styles:
                card:
                  - margin-top: 10px
                  - margin-left: 8px
                  - width: 60px
                  - height: 60px
                  - border-radius: 15px
                  - background-color: var(--primary-background-color)
                icon:
                  - color: var(--primary-text-color)
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: input_alexa
                  num_repeats: 5
                  entity_id: remote.xiaomi
              type: 'custom:button-card'
          type: 'custom:hui-horizontal-stack-card'
      show_header_toggle: false
      style: |
        ha-card {
          background-color: var(--primary-background-color);
          width: 250px;
          border-radius: 10px;
          margin: 10px auto;
          box-shadow:
            {% if is_state('sun.sun', 'above_horizon') %}
              -5px -5px 8px rgba(255,255,255,.5),5px 5px 8px rgba(0,0,0,.03);
            {% elif is_state('sun.sun', 'below_horizon') %}
              -5px -5px 8px rgba(50, 50, 50,.2),5px 5px 8px rgba(0,0,0,.08);
            {% endif %}
        }
      type: entities
    title: Remote

# Lovelace views, all the views are inside the views folder
views: 
  !include_dir_merge_list views/
